pulsejet/memories

lib/Command/Index.php
Besides adding a percentage progress, this also exploits the ConsoleSectionOutput capability of Symfony to simplify the carriage return gymnastics and to fix it for paths exceeding the console window width.
Tested on NC 25.0.1
=> Report progress during indexing

Makefile
Mark all rules that doesn't depend on files as PHONY to avoid any future conflict.
=> Add explicit .PHONY rules

Makefile
Hey, thanks for creating this great app. 
When I tried to set up a development environment on MacOS, I received the error `mkdir: illegal option -- -` from the `make` command. This is because the long form parameters for `mkdir` are not available on MacOS. I believe the `-p` option is more widely available.
=> Use mkdir -p instead of mkdir --parents

src/components/SelectionManager.vue, src/components/modal/MoveToFolderModal.vue, src/services/dav/base.ts
I've been looking for a 'perfect' self hosted gallery app for some time, and this is the best I could find so far. So thanks for this project!
While I am using this app though, I notice couple of features fell short, which are important for my use-case. So moving multiple photos from timeline and folders to another folder is the one I need at the moment (effectively fixes #204 - only move part though). So I decided to implement this. I understand that if this won't be prioritized (I'll use my fork anyway 😄) or cancelled all together.
Couple of notes:
- Webdav natively supports `MOVE`, so just using it as similar to Nextcloud files.
- If the target exists, it'll fail. (again, same behavior with Nextcloud files).
- Not enabling move in albums and archive as it would probably be doing …
=> Add move to folder feature

lib/Controller/PeopleController.php, lib/Db/TimelineQueryPeopleFaceRecognition.php
It was working incorrectly since my last PR. Sorry.
Note that may seem useful to show them all, but it ends up being a never-ending task that annoys the user.
On the other hand, I made two public functions to improve the readability of the controller code.
=> Face Recognition: Fix query to not show individual clusters

lib/Controller/AlbumsController.php
`/memories/api/albums` API returns a JSON object (expected: JSON array) when some albums are filtered [here](https://github.com/pulsejet/memories/blob/e207d3a8c55c7c831c6202fb7961f5826aeda00a/lib/Controller/AlbumsController.php#L59-L66).
This causes the following error.
`json_encode` (called in [JSONResponse](https://github.com/pulsejet/memories/blob/e207d3a8c55c7c831c6202fb7961f5826aeda00a/lib/Controller/AlbumsController.php#L68)) generates JSON object when non sequential array is given.
Use `array_values` to convert to sequential array.
=> Fix /memories/api/albums API to return JSON array

lib/Cron/IndexJob.php
An indexing cron job not finishing is just normal operation, so we shouldn't emit a warning for it. This commit emits a info instead when this happens.
While we are at it, we also emit a info message if the indexing was successful.
Fixes #605.
=> Avoid showing "Memories: Indexing process stopped before completion. Will continue on next run" as a warning

lib/AppInfo/Application.php
Videos from my (old) Powershot A80 (avi files) are not processed by memories because their mime type is 'video/x-msvideo'.
Would it be possible to add this mime type by default ?
Thank you very much for your work.
David
Edit: Just a few more information: 
I tested it after adding the type in Application.php and it works perfectly.
Here is an example of these video files:
[MVI_4254.zip](https://github.com/pulsejet/memories/files/11302932/MVI_4254.zip)
=> Add x-msvideo mime type

src/components/SelectionManager.vue, src/types.ts
=> fix: Fix a bug that caused some unassigned face photos to be unselectable

lib/Command/Index.php
- For tens of thousands of users on an instance, running the index command is a must before enabling the app
- Sometimes,  need to re-run for a particular group so added `group`  option
- Also cleanup itself takes a few minutes and when running per-user, it wastes a lot of time, so added `skip-cleanup` option that defaults to `false`
=> Add per-group and skip cleanup options

lib/Controller/OtherController.php, lib/SystemConfigDefault.php, src/components/Settings.vue, src/components/admin/AdminTypes.ts, src/components/admin/sections/FileSupport.vue, src/components/viewer/Viewer.vue, src/mixins/UserConfig.ts, src/services/static-config.ts, src/types.ts
Add seperate full res configuration for public shares to the admin settings. 
Fixes: https://github.com/pulsejet/memories/issues/662
=> Add configuration for full res on zoom and full res always for public shares

README.md
This adds a step to the "development setup" part of the readme that defines which programs have to be installed before make dev-setup is run.
I added Composer and node.js 18 becaues that are the programs that I had to install, but it is possible, that more programs are needed. I'm also not completly sure if 18 is the correct version of node.js but as far as I can tell from the package.json it is.
=> Readme add required programs

src/components/ClusterView.vue, src/components/top-matter/ClusterTopMatter.vue
This Pull-Request contains two changes related to translation of tag names.
The first change fixes a Problem, that the title of tag detail pages like /apps/memories/tags/Frog wasn't translated even though the name of is Tag is translated on the overview page.
The second change sorts the Tags on the overview page in the correct order for the current language. Previously this was sorted by english names and the translated names were shown.
=> Translate tag names

appinfo/routes.php, lib/Controller/FoldersController.php, lib/Db/FsManager.php, src/components/Timeline.vue, src/components/frame/Folder.vue, src/components/top-matter/DynamicTopMatter.vue, src/components/top-matter/FolderTopMatter.vue, src/components/top-matter/TopMatter.vue, src/router.ts, src/types.ts
Implemented feature request #324 
API endpoint `/api/folders/sub` is now marked as `@PublicPage`, but I removed the `path` information from the returned data. This was the absolute path, revealing the name of folders outside the share. The web client now compute the path by itself, see bellow.
- If a folder `child` is in a folder `parent`, the web client assumes that its path is `{parent path}/{child name}`. Looking at the code that was present before, it seems that it may not be always the case? Maybe?
- Route `/s/{token}/authenticate/{redirect}` is in conflict with `/s/{token}/{path}`. It's only an issue if you refresh the page on a directory which parent is named `authenticate`, which parent is the share root. So it's highly unlikely that this will cause any issue, but it's cleaner if …
=> share: show directory structure

docs/troubleshooting.md
It might be a good idea if another nixos user can cross-check if thats really fixing the issue.
For reference i did install memories impurely via the nextcloud app store and *not* via `services.nextcloud.extraApps`.
=> docs: Add nixos section to get automatic indexer running

docs/hw-transcoding.md
`/dev/dri/renderD128 does not belongs to the `video` group, but to the `render` group. 
Following the old steps will cause an `VA-API device (/dev/dri/renderD128) has incorrect permissions on the Memories config` error
=> Fix: correct group assigment for HW Acceleration

.devcontainer/docker-compose.yml
It fixes my problem when I tried to develop something using devcontainer and GitHub Codespaces.
=> fix: Ensure read-write permissions for devcontainer

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/gallery/memories/service/ImageService.kt
I found that the [previous PR](https://github.com/pulsejet/memories/pull/1118) was only one step to fixing the issue. Just like before, android:requestLegacyExternalStorage is needed for permission purposes, which fixes the EXIF data and full image on zoom. However, the thumbnail generation was still not working as the URI returned by ContentUris.withAppendedId was incorrect, so I used a different approach to get the correct URI.
I could not easily test on newer devices but on my Android 10, this fixes #1000.
=> android: show local files on older devices

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/gallery/memories/MainActivity.kt
For some reason, I wasn´t able to find out why, on my phone (Pixel 7, android 14) is main activity always recreated when screen is rotated, and app always forget in which state it was. I was not able to replicate this behavior in android studio emulator, which is weird. It is really annoying so I decided  to add feature to restore MainActivity from previous state.
For the same reason no full screen setting (hide status bar) was called so I added it to onCreate function. All edits would be called once on devices without this problem, which should be fine, and this will work as back up for devices which do have same problem. 
Bonus is, that this will work every time, that for example split screen should now work better (App will not "restart").
=> Android: Added onSaveInstanceState

docs/hw-transcoding.md
On Windows, users don't need to install the container-tookit to enable gpu support in container. Add a verified tip for this senerio.
=> go-vod: update hw transcoding advice for wsl

lib/Db/AlbumsQuery.php, src/components/frame/Cluster.vue, src/components/modal/AlbumsList.vue, src/components/top-matter/AlbumDynamicTopMatter.vue, src/components/top-matter/DynamicTopMatter.vue, src/typings/cluster.d.ts
This is a draft PR that attempts to improve memories' albums view by displaying essential metadata.
First 2 commits attempt to display the "shared" status of an album. This makes it easier to see which albums are private or not and which users have access/contributed to a specific album.
1. show whether an album is shared in the albums overview listings (i.e., add a "shared" keyword, similar to how it's done for Google Photos and [nc-photos](https://gitlab.com/nkming2/nc-photos)).  (aside: not sure what is desired re translations, but I went for "Shared Album" for now as that is already in the translations currently; adding a more brief "Shared" translation keyword would probably be even more concise in the UI though..)
2. display the avatars of album collaborators above the album …
=> Display album metadata (location field, collaborators)

docs/install.md
to fix #1106 and #1309 
Nextcloud 30 still lists PostgreSQL 12/13/14/15/16 as recommended and still supports down to PostgreSQL 10.
=> Update install.md with postgresql >=v15

lib/Exif.php
When metadata/EXIF data are written in Memories, the native Nextcloud metadata handling isn't triggered since $file->touch() alone doesn't propagate these changes. This PR adds dispatching of the nodeWritten event to ensure proper metadata synchronization. 
Most EXIF tags are not present in the metadata one gets with the native $file->getMetadata() anyway, but e.g. the important copyright tag is.
Also other apps might depend on this event to properly handle changes.
=> Exif: dispatch nodeWrittenEvent

src/components/viewer/PsLivePhoto.ts
This PR fixes a small issue encountered when autoplaying + auto-repeating a series of successive live photos in the image viewer.
For some reason, not sure why, `this.liveState.playing` remembers the state of the _previous_ image. Thus, when switching between successive live photos, every second photo get incorrectly paused instead of played on load.
Using the builtin `video.paused` attribute seems to fix this.
=> fix: autoplay successive live photos

.gitattributes
This fixes the line endings for (at least) `.devcontainer/postCreate.sh` when git cloning the repository on Windows, and then opening the devcontainer (Linux environment).
Throws `line 25: $'\r': command not found` otherwise.
=> Ensure consistent .sh line endings

.github/workflows/docs.yaml, .github/workflows/go-vod.yml, .github/workflows/release.yaml
They bumped some major Action versions due to Node.js upgrades and similar, but none of the potential breaking changes seem to matter to Memories.
=> Chore: Update CI actions

lib/Command/MigrateGoogleTakeout.php
The Google Takeout feature has changed. The downloaded tarball will contain the JSON metadata but with a different name, including - fully or partially - the string "supplemental-metadata" before the `.json` terminator.
This commit modifies the logic to look for a file matching a RegExp (https://regex101.com/r/rXUYj4/1) rather than just appending a `.json` suffix.
=> [Bug] Takeout: Invalid JSON name

appinfo/info.xml
(rendered in Nextcloud app store infobox)
Docs: For better reachability by users
Donation: For better visibility to users (who will not visit github page). For preview of result see for example https://apps.nextcloud.com/apps/passwords
=> App metadata: add docs and donation links

lib/Db/TimelineWrite.php, lib/Exif.php, lib/Settings/SystemConfig.php
The TZ environment variable is not set on many machines and date_default_timezone_get only works if the timezone has been set elsewhere. Instead, this approach relies on the Nextcloud server configuration for the timezone.
Closes #1240
See: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#default-timezone
=> Use system default for timezone
